### ISSUE TITLE
Cannot specify sensors in the configuration

### ISSUE THREAD

**Issue by rickyclegg** [MatsNl/pyatag-ha#5]
I'm running HA with Hassio on a Raspberry Pi.

I want to add a sensor for the current temperature which is not in the default sensors.
Whenever I try and specify any sensors in the config it always stops my restart saying that the configuration is not valid. If I delete all of the sensors it works fine.

Error in log:
```
Invalid config for [atag]: value is not allowed @ data['atag']['sensors'][0]. Got 'device_id'
value is not allowed @ data['atag']['sensors'][1]. Got 'device_status'
value is not allowed @ data['atag']['sensors'][2]. Got 'current_temperature'
value is not allowed @ data['atag']['sensors'][3]. Got 'temperature'. (See /config/configuration.yaml, line 37). 
```

Config
```
atag:
  host: 192.168.1.1
  email: xxx
  port: 10000
  scan_interval: 30
  sensors:
    - device_id
    - device_status
    - current_temperature
    - temperature
    - ch_water_pressure
```

Any ideas what I'm doing wrong?
